name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - '.gitignore'
      - 'scripts/**'
      - '.github/workflows/cd.yml'
      - '.goreleaser.yml'
      - '.github/workflows/ci-skip.yml'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**.md'
      - '.gitignore'
      - 'scripts/**'
      - '.github/workflows/cd.yml'
      - '.goreleaser.yml'
      - '.github/workflows/ci-skip.yml'

jobs:
  pr-checks:
    name: Verify All Checks Passed
    runs-on: ubuntu-latest
    steps:
      - run: echo "No source code changes detected. Skipping CI successfully!"
