name: Security Gates

on:
  workflow_call:

permissions:
  contents: read

jobs:
  sast:
    runs-on: ubuntu-latest
    name: Gosec Scan
    env:
      GO111MODULE: on
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

  sca:
    runs-on: ubuntu-latest
    name: Trivy SCA Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Trivy SCA Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "fs"
          input: "."
          format: "table"
          exit-code: 1
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"

  image-scan:
    runs-on: ubuntu-latest
    name: Trivy Image Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build image
        run: docker build -t pombohook:latest .
        
      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "image"
          input: "pombohook:latest"
          format: "table"
          exit-code: 1
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

  


      

        
        
        
    